# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean Blanton
email: seanblanton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sean Blanton is a designer living in Seattle, Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sean-blanton.com" # the base hostname & protocol for your site
twitter_username: seancblanton
github_username:  seanblanton

# Build settings
markdown: kramdown

exclude: ['node_modules', ‘css’, ‘_scss’, 'README.md'] 
keep_files: ['_site/css']
category-list: [Recent projects]
category: [Work, About]
